
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    branches:
      - main
    types:
      - published
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Project name to pack and publish
  PROJECT_NAME: ServerTools.ServerCommands
  # GitHub Packages Feed settings
  GITHUB_FEED: https://nuget.pkg.github.com/hgjura/
  GITHUB_USER: hgjura
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
     
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/${{ env.PROJECT_NAME }}/
    
    - name: Build
      run: |
        dotnet build --no-restore --configuration Release
      working-directory: ./src/${{ env.PROJECT_NAME }}/
    
    - name: Set secrets for tests 
      run: |
        dotnet user-secrets set "StorageAccountName" ${{ secrets.ACCT_NAME }}
        dotnet user-secrets set "StorageAccountKey" ${{ secrets.ACCT_KEY }}
      working-directory: ./tests/ServerTools.ServerCommands.Tests/

    - name: Test
      run: |
        dotnet test --verbosity minimal --configuration Release
      working-directory: ./

    - name: Get Last Release Id
      id: latest-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}

    - name: Pack CI
      if: github.event_name != 'release'
      run: |
          VER=${{ steps.latest-release.outputs.release }}
          VER="${VER//v}"
          IFS=. read -r a b c <<< "$VER"
          echo Next Version: "$a.$b.$((c+1))"-${GITHUB_RUN_ID}
          dotnet pack --configuration Release /p:Version="$a.$b.$((c+1))"-${GITHUB_RUN_ID} --no-build --output .

    - name: Pack Release
      if: github.event_name == 'release'
      run: |
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
          echo Version: $VERSION
          VERSION="${VERSION//v}"
          echo Clean Version: $VERSION
          dotnet pack --configuration Release /p:Version=$VERSION --no-build --output .
  
    - name: Publish to GitHub PM
      run: dotnet nuget push ./**/*.nupkg --source ${GITHUB_FEED}/index.json --api-key ${GITHUB_TOKEN}

    - name: Publish to Nuget PM
      if: github.event_name == 'release'
      run: dotnet nuget push ./**/*.nupkg --source ${NUGET_FEED}/index.json --api-key ${NUGET_API_KEY}

